#!/bin/bash

alias rm="rm -i"
source /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.24.06/x86_64-centos7-gcc48-opt/bin/thisroot.sh
#source /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.26.02/x86_64-centos8-gcc85-opt/bin/thisroot.sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/
